apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: coyz7h2ns-go 
  janus-idp.io/tekton: coyz7h2ns-go
  backstage.io/kubernetes-id: coyz7h2ns-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: coyz7h2ns-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  