apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: coyz7h2ns-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: coyz7h2ns-go 
  name: coyz7h2ns-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: coyz7h2ns-go 
